ALTER TABLE services
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS duration_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE services
    ALTER COLUMN price TYPE DOUBLE PRECISION USING price::double precision;

ALTER TABLE payments
    ALTER COLUMN amount TYPE DOUBLE PRECISION USING amount::double precision;
