### Variáveis Globais
@baseUrl = http://localhost:8080
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtYW5pY3VyZV9hcGkiLCJzdWIiOiJhZG1pbkBzYWxhby5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsImV4cCI6MTc3ODUzMTQ5Nn0.FsgqoOL0GVWbnY_ABz_ggqAtyUyrHTzbfFl26PgNZ9Q

POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "admin@salao.com",
  "password": "admin123456"
}


### Criar novo cliente (Acesso Público)
POST {{baseUrl}}/api/v1/clients
Content-Type: application/json

{
  "name": "Luis Gustavo",
  "email": "silva@gmail.com",
  "password": "654321",
  "phone": "11999999999"
}

### Listar todos os clientes (Requer ADMIN)
GET {{baseUrl}}/api/v1/clients
Authorization: Bearer {{token}}

### Buscar cliente por ID
GET {{baseUrl}}/api/v1/clients/34
Authorization: Bearer {{token}}




### Criar novo profissional
POST {{baseUrl}}/api/v1/professionals
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Luis Gonzaga",
  "email": "json@gamil.com",
  "password": "adm12456",
  "phone": "11888888888",
  "specialty": "Unhas de Gel"
}

### Listar profissionais
GET {{baseUrl}}/api/v1/professionals
Authorization: Bearer {{token}}

### Criar agendamento
POST {{baseUrl}}/api/v1/appointments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientId": 1,
  "professionalId": 1,
  "serviceId": 1,
  "dateTime": "2026-10-10T14:30:00"
}

### Criar um serviço (Requer ADMIN)
POST {{baseUrl}}/api/v1/services
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alongamento de Unha",
  "description": "Corte, lixamento e esmaltação comum",
  "price": 50.00,
  "duration": 45
}


### Listar serviços
GET {{baseUrl}}/api/v1/services
Authorization: Bearer {{token}}
Content-Type: application/json


### Buscar um serviço por ID
GET  {{baseUrl}}/api/v1/services/3
Content-Type: application/json
Authorization: Bearer {{token}}

### Listar meus agendamentos (Cliente)
GET {{baseUrl}}/api/v1/appointments/client/1
Authorization: Bearer {{token}}


### Simular Pagamento
POST {{baseUrl}}/api/v1/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "appointmentId": 1,
  "amount": 50.00,
  "paymentMethod": "PIX"
}

# ==========================================
# 🕵️‍♂️ TESTE DE SEGURANÇA (PROTEÇÃO IDOR)
# ==========================================

### 1. Fazer login como o Cliente David
POST {{baseUrl}}/login
Content-Type: application/json

{
  "login": "david@teste.com",
  "password": "123456"
}

### Após rodar o login acima, copie o token dele e substitua o texto abaixo:
@tokenCliente = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJtYW5pY3VyZV9hcGkiLCJzdWIiOiJkYXZpZEB0ZXN0ZS5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzc4MTI2NjMxfQ.AM44mlUG91k74rPDkoYAd79_hG-OXKR5qxRrg6QWLio

### 2. David acessando a PRÓPRIA agenda (ID 1) -> DEVE RETORNAR 200 OK
GET {{baseUrl}}/api/v1/appointments/client/1
Authorization: Bearer {{tokenCliente}}

### 3. David tentando invadir a agenda de OUTRA PESSOA (ID 2) -> DEVE RETORNAR 403 FORBIDDEN
GET {{baseUrl}}/api/v1/appointments/client/2
Authorization: Bearer {{tokenCliente}}



### Health Check (Verificar se a API está saudável)
GET {{baseUrl}}/actuator/health
Authorization: Bearer {{token}}

### Listar todas as métricas disponíveis
GET {{baseUrl}}/actuator/metrics
Authorization: Bearer {{token}}

### Ver o tempo de criação de agendamentos (A métrica que você criou!)
GET {{baseUrl}}/actuator/metrics/api_appointment_creation_time
Authorization: Bearer {{token}}

### Ver métricas no formato Prometheus
GET {{baseUrl}}/actuator/prometheus
Authorization: Bearer {{token}}
