spring:
  application:
    name: manicure-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:manicure_db}${DB_SSL_PARAMS:}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

server:
  port: ${PORT:8080}

logging:
  level:
    br.com.davidds5.manicure_api: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb.core: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
